services:
  database:
      image: postgres:17
      env_file: .env
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_APP}
        POSTGRES_DB: ${POSTGRES_DB_APP}
      volumes:
        - db-app:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - network_app

  football-api:
    build:
      context: .
      dockerfile: FastAPI_App/Dockerfile.api
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - network_app
    depends_on:
      - postgres-app

  football-ml:
    build:
      context: .
      dockerfile: FastAPI_ML/Dockerfile.api
    ports:
      - "8001:8001"
    env_file: .env
    networks:
      - network_ml
      - network_app
    depends_on:
      - postgres-ml

  football-front:
    build:
      context: .
      dockerfile: match_prediction_app-front/Dockerfile.front
    ports:
      - "8080:8080"
    networks:
      - network_app
    depends_on:
      - football-api
      - football-ml

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - network_app
      - network_ml
    depends_on:
      - football-api
      - football-ml
      - football-front

networks:
  network_app:
  network_ml:

volumes:
  db-app:
  db-ml:
  caddy_data:
  caddy_config: